# Generated by Django 4.2 on 2024-07-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0002_extradata_alter_ceo_avatar_alter_ceo_descriptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extradata",
            name="aboutUsContent",
            field=models.TextField(default="SOME STRING", verbose_name="متن درباره ما"),
        ),
        migrations.AddField(
            model_name="extradata",
            name="backGroundImage1",
            field=models.ImageField(
                default="media\\defaults\\male_user.png",
                upload_to="extraData/",
                verbose_name="تصویر بک گراند۱",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extradata",
            name="backGroundImage2",
            field=models.ImageField(
                default="media\\defaults\\male_user.png",
                upload_to="extraData/",
                verbose_name="تصویر بک گراند۲",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extradata",
            name="logo",
            field=models.ImageField(
                default="media\\defaults\\male_user.png",
                upload_to="logo/",
                verbose_name="لوگو",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="satisfaction",
            name="image",
            field=models.ImageField(
                default="media/defaults/male_user.png",
                upload_to="satisfaction/",
                verbose_name="تصویر",
            ),
        ),
    ]
