# Generated by Django 4.2 on 2024-07-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0003_extradata_aboutuscontent_extradata_backgroundimage1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ceo",
            name="telegram",
        ),
        migrations.AlterField(
            model_name="ceo",
            name="avatar",
            field=models.ImageField(
                default="media\\defaults\\male_user.png",
                upload_to="ceo/",
                verbose_name="تصویر شخص ",
            ),
        ),
        migrations.AlterField(
            model_name="ceo",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="شماره موبایل"),
        ),
        migrations.AlterField(
            model_name="extradata",
            name="NumberofProduct",
            field=models.PositiveIntegerField(verbose_name="میزان تولید در روز"),
        ),
        migrations.AlterField(
            model_name="extradata",
            name="YearofExperience",
            field=models.PositiveIntegerField(verbose_name="چند سال تجربه؟"),
        ),
        migrations.AlterField(
            model_name="extradata",
            name="active",
            field=models.BooleanField(verbose_name="نمایش داده شود؟"),
        ),
    ]
