# Generated by Django 4.2 on 2024-07-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0004_remove_ceo_telegram_alter_ceo_avatar_alter_ceo_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceo",
            name="descriptions",
            field=models.TextField(max_length=225, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="satisfaction",
            name="image",
            field=models.ImageField(
                default="defaults/male_user.png",
                upload_to="satisfaction/",
                verbose_name="تصویر",
            ),
        ),
    ]
