# Generated by Django 4.2 on 2024-07-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0006_product_alter_ceo_avatar_alter_satisfaction_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=False, verbose_name="نمایش داده شود؟"),
            preserve_default=False,
        ),
    ]
