# Generated by Django 4.2 on 2024-07-19 06:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0007_product_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="createdTime",
            field=django_jalali.db.models.jDateField(
                null=True, verbose_name="سال ساخت (اختیاری)"
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="title",
            field=models.CharField(max_length=50, verbose_name="موضوع"),
        ),
    ]
