# Generated by Django 4.2 on 2024-07-19 06:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0008_alter_product_createdtime_alter_slider_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="createdTime",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="سال ساخت (اختیاری)"
            ),
        ),
    ]
