# Generated by Django 4.2 on 2024-07-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0009_alter_product_createdtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="createdTime",
        ),
    ]
