# Generated by Django 4.2 on 2024-07-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hodka", "0010_remove_product_createdtime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ceo",
            options={"verbose_name": "مدیران", "verbose_name_plural": "مدیران"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "پیغام ها", "verbose_name_plural": "پیغام ها"},
        ),
        migrations.AlterModelOptions(
            name="extradata",
            options={
                "verbose_name": "داده های دیگر",
                "verbose_name_plural": "داده های دیگر",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "محصولات", "verbose_name_plural": "محصولات"},
        ),
        migrations.AlterModelOptions(
            name="satisfaction",
            options={"verbose_name": "رضایتمندی", "verbose_name_plural": "رضایتمندی"},
        ),
        migrations.AlterModelOptions(
            name="slider",
            options={"verbose_name": "اسلایدر", "verbose_name_plural": "اسلایدر"},
        ),
    ]
